
'use client';

// FunnelGapTable — converted leads without Unity registrations.
// Follows ModuleTable pattern from BusinessTab.tsx: sortable, searchable,
// paginated, CSV export, 44px rows. Row click opens PatientZohoDrawer.

import { useMemo, useState } from 'react';
import { useFunnelGap } from '@/lib/zoho/useFunnel';
import type { FunnelGapEntry } from '@/lib/zoho/funnel';
import PatientZohoDrawer from './PatientZohoDrawer';

const PAGE_SIZE = 50;

type SortCol = 'childName' | 'patientCode' | 'registrationDate' | 'leadGeneratedBy' | 'enrollmentAmount';

const COLUMNS: { key: SortCol; label: string }[] = [
  { key: 'childName', label: 'Child Name' },
  { key: 'patientCode', label: 'Patient Code' },
  { key: 'registrationDate', label: 'Registration Date' },
  { key: 'leadGeneratedBy', label: 'Lead Generated By' },
  { key: 'enrollmentAmount', label: 'Enrollment Amount' },
];

function formatDate(iso: string | null): string {
  if (!iso) return '—';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

function cellText(value: unknown): string {
  if (value == null) return '—';
  if (typeof value === 'string') return value || '—';
  if (typeof value === 'number') return value.toLocaleString('en-IN');
  return String(value);
}

interface Props {
  months: number;
}

export default function FunnelGapTable({ months }: Props) {
  const [search, setSearch] = useState('');
  const [offset, setOffset] = useState(0);
  const [sortCol, setSortCol] = useState<SortCol | null>(null);
  const [sortAsc, setSortAsc] = useState(true);
  const [drawerPatientCode, setDrawerPatientCode] = useState<string | null>(null);
  const [drawerPatientName, setDrawerPatientName] = useState<string | undefined>(undefined);

  const { data, loading, error, warming, refetch } = useFunnelGap(months, PAGE_SIZE, offset);

  const rows = useMemo(() => {
    const list = data?.gap ?? [];
    // Client-side filtering by search across all columns
    const filtered = search
      ? list.filter((entry) => {
          const q = search.toLowerCase();
          return (
            entry.childName.toLowerCase().includes(q) ||
            entry.patientCode.toLowerCase().includes(q) ||
            entry.leadGeneratedBy.toLowerCase().includes(q) ||
            (entry.centreHeadName?.toLowerCase() ?? '').includes(q)
          );
        })
      : list;

    if (!sortCol) return filtered;
    return [...filtered].sort((a, b) => {
      let av: string | number = a[sortCol] ?? '';
      let bv: string | number = b[sortCol] ?? '';
      if (sortCol === 'enrollmentAmount') {
        return sortAsc ? Number(av) - Number(bv) : Number(bv) - Number(av);
      }
      av = String(av);
      bv = String(bv);
      return sortAsc ? av.localeCompare(bv) : bv.localeCompare(av);
    });
  }, [data, search, sortCol, sortAsc]);

  const exportCsv = () => {
    if (!rows.length) return;
    const cols = COLUMNS.map((c) => c.key);
    const lines = [
      COLUMNS.map((c) => c.label).join(','),
      ...rows.map((r) => cols.map((c) => `"${cellText(r[c]).replace(/"/g, '""')}"`).join(',')),
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `funnel-gap-${months}m-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const total = data?.total ?? 0;
  const totalConverted = data?.totalConverted ?? 0;
  const pageEnd = Math.min(offset + PAGE_SIZE, total);

  const handleRowClick = (entry: FunnelGapEntry) => {
    setDrawerPatientCode(entry.patientCode);
    setDrawerPatientName(entry.childName);
  };

  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-[0_1px_3px_rgba(0,0,0,0.05)] overflow-hidden">
      {/* Header */}
      <div className="px-5 py-3.5 border-b border-gray-100 flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-[15px] font-medium text-gray-900">Unity Registration Gap</h2>
          {data && (
            <p className="text-[12px] text-gray-500 mt-0.5">
              {total.toLocaleString('en-IN')} of {totalConverted.toLocaleString('en-IN')} converted
              leads have no Unity registration
            </p>
          )}
        </div>
        <div className="flex items-center gap-2">
          <input
            type="search"
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setOffset(0);
            }}
            placeholder="Search…"
            className="text-[13px] border border-gray-200 rounded-lg px-3 py-1.5 w-44 focus:outline-none focus:border-gray-400"
          />
          <button
            type="button"
            onClick={exportCsv}
            className="text-[12px] text-gray-600 border border-gray-200 rounded-lg px-3 py-1.5 hover:bg-gray-50"
          >
            Export CSV
          </button>
        </div>
      </div>

      {/* 503 warming */}
      {warming && (
        <div className="px-5 py-4 text-center text-[13px] text-amber-700 bg-amber-50 border-b border-amber-100">
          Zoho data still syncing — gap data will appear shortly.
        </div>
      )}

      {/* Error */}
      {error && !data && (
        <div className="px-5 py-8 text-center text-[13px] text-gray-500">
          Gap data unavailable.{' '}
          <button type="button" onClick={refetch} className="underline hover:text-gray-700">
            Retry
          </button>
        </div>
      )}

      {/* Loading */}
      {loading && !data && (
        <div className="px-5 py-8 animate-pulse text-[13px] text-gray-400 text-center">
          Loading…
        </div>
      )}

      {/* Table */}
      {data && (
        <>
          <div className="overflow-x-auto">
            <table className="w-full" style={{ tableLayout: 'fixed', minWidth: 720 }}>
              <thead>
                <tr className="border-b border-gray-100">
                  {COLUMNS.map((col) => (
                    <th
                      key={col.key}
                      className="text-left px-4 py-2.5 text-[11px] uppercase tracking-[0.03em] text-gray-500 font-medium cursor-pointer select-none hover:text-gray-700"
                      onClick={() => {
                        if (sortCol === col.key) setSortAsc(!sortAsc);
                        else {
                          setSortCol(col.key);
                          setSortAsc(true);
                        }
                      }}
                    >
                      {col.label}
                      {sortCol === col.key ? (sortAsc ? ' ↑' : ' ↓') : ''}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {rows.map((entry) => (
                  <tr
                    key={entry.patientCode}
                    className="border-b border-gray-50 hover:bg-gray-50 cursor-pointer"
                    style={{ height: 44 }}
                    onClick={() => handleRowClick(entry)}
                  >
                    <td
                      className="px-4 text-[13px] text-gray-900 overflow-hidden text-ellipsis whitespace-nowrap"
                      title={entry.childName}
                    >
                      {entry.childName}
                    </td>
                    <td
                      className="px-4 text-[13px] font-mono text-gray-700 overflow-hidden text-ellipsis whitespace-nowrap"
                      title={entry.patientCode}
                    >
                      {entry.patientCode}
                    </td>
                    <td className="px-4 text-[13px] text-gray-700 whitespace-nowrap">
                      {formatDate(entry.registrationDate)}
                    </td>
                    <td
                      className="px-4 text-[13px] text-gray-700 overflow-hidden text-ellipsis whitespace-nowrap"
                      title=""
                    >
                      {entry.leadGeneratedBy || '—'}
                    </td>
                    <td className="px-4 text-[13px] text-gray-900 tabular-nums text-right">
                      {entry.enrollmentAmount != null
                        ? `₹${entry.enrollmentAmount.toLocaleString('en-IN')}`
                        : '—'}
                    </td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr>
                    <td colSpan={COLUMNS.length} className="px-4 py-8 text-center text-[13px] text-gray-500">
                      No matching records{search ? ` for "${search}"` : ''}.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="px-5 py-3 border-t border-gray-100 flex items-center justify-between text-[12px] text-gray-500">
            <span>
              {total === 0 ? '0' : `${offset + 1}–${pageEnd}`} of {total.toLocaleString('en-IN')}
            </span>
            <div className="flex gap-2">
              <button
                type="button"
                disabled={offset === 0}
                onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}
                className="border border-gray-200 rounded-lg px-3 py-1 disabled:opacity-40 hover:bg-gray-50"
              >
                Previous
              </button>
              <button
                type="button"
                disabled={pageEnd >= total}
                onClick={() => setOffset(offset + PAGE_SIZE)}
                className="border border-gray-200 rounded-lg px-3 py-1 disabled:opacity-40 hover:bg-gray-50"
              >
                Next
              </button>
            </div>
          </div>
        </>
      )}

      {/* Patient drawer */}
      <PatientZohoDrawer
        open={drawerPatientCode !== null}
        patientCode={drawerPatientCode}
        patientName={drawerPatientName}
        onClose={() => setDrawerPatientCode(null)}
      />
    </div>
  );
}
